/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-11-12 15:51:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/configuration.jsp", Long.valueOf(1510484577539L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1510487600816L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1510501060669L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("    Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("    contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("    this work for additional information regarding copyright ownership.\n");
      out.write("    The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("    the \"License\"); you may not use this file except in compliance with\n");
      out.write("    the License.  You may obtain a copy of the License at\n");
      out.write(" \n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write(" \n");
      out.write("    Unless required by applicable law or agreed to in writing, software\n");
      out.write("    distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("    See the License for the specific language governing permissions and\n");
      out.write("    limitations under the License.\n");
      out.write(" -->\n");
      out.write("<!--\n");
      out.write("    Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("    contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("    this work for additional information regarding copyright ownership.\n");
      out.write("    The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("    the \"License\"); you may not use this file except in compliance with\n");
      out.write("    the License.  You may obtain a copy of the License at\n");
      out.write(" \n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write(" \n");
      out.write("    Unless required by applicable law or agreed to in writing, software\n");
      out.write("    distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("    See the License for the specific language governing permissions and\n");
      out.write("    limitations under the License.\n");
      out.write(" -->\n");
      out.write("<!--\n");
      out.write("    Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("    contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("    this work for additional information regarding copyright ownership.\n");
      out.write("    The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("    the \"License\"); you may not use this file except in compliance with\n");
      out.write("    the License.  You may obtain a copy of the License at\n");
      out.write(" \n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write(" \n");
      out.write("    Unless required by applicable law or agreed to in writing, software\n");
      out.write("    distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("    See the License for the specific language governing permissions and\n");
      out.write("    limitations under the License.\n");
      out.write(" -->\n");

/* Author: Andrew C. Oliver (acoliver2@users.sourceforge.net) */
String appTitle = "Apache Lucene Example - Intranet Server Search Application";
/* make sure you point the below string to the index you created with IndexHTML */
String indexLocation = "W:\\Program\\eclipse\\WorkSpace\\Lucene";
String appfooter = "Apache Lucene Template WebApp 1.0";

      out.write('\n');
      out.write('\n');
      out.write('\n');
 /* Author: Andrew C. Oliver (acoliver2@users.sourceforge.net */ 
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>");
      out.print(appTitle);
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<p align=\"center\">\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</p>\n");
      out.write('\n');
      out.write('\n');
 /* Author: Andrew C. Oliver (acoliver2@users.sourceforge.net) */ 
      out.write("\n");
      out.write("<img src = \"Logo.jpg\" style=\"width : 450px;  position:relative; left:32%\"/>\n");
      out.write("<center> \n");
      out.write("\t<form name=\"search\" action=\"results.jsp\" method=\"get\" style=\"left:30%\">\n");
      out.write("\t\t<p>\n");
      out.write("\t\t\t<input name=\"query\" size=\"44\" placeholder=\"Type your document here...\"/>&nbsp;\n");
      out.write("\t\t</p>\n");
      out.write("\t\t<p>\n");
      out.write("            Search method\n");
      out.write("            <select>\n");
      out.write("                    <option value=\"volvo\">Cosine Similarity</option>\n");
      out.write("                    <option value=\"saab\">Page rank</option>\n");
      out.write("                    <option value=\"opel\">Cosine Sim & PageRank</option>\n");
      out.write("            </select>\n");
      out.write("            <br></br>\n");
      out.write("\t\t\t<input name=\"maxresults\" size=\"4\" value=\"10\"/>&nbsp;Results Per Page&nbsp;\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Search\"/>\n");
      out.write("\t\t</p>\n");
      out.write("    </form>\n");
      out.write("</center>\n");
      out.write("<!--\n");
      out.write("    Licensed to the Apache Software Foundation (ASF) under one or more\n");
      out.write("    contributor license agreements.  See the NOTICE file distributed with\n");
      out.write("    this work for additional information regarding copyright ownership.\n");
      out.write("    The ASF licenses this file to You under the Apache License, Version 2.0\n");
      out.write("    the \"License\"); you may not use this file except in compliance with\n");
      out.write("    the License.  You may obtain a copy of the License at\n");
      out.write(" \n");
      out.write("        http://www.apache.org/licenses/LICENSE-2.0\n");
      out.write(" \n");
      out.write("    Unless required by applicable law or agreed to in writing, software\n");
      out.write("    distributed under the License is distributed on an \"AS IS\" BASIS,\n");
      out.write("    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n");
      out.write("    See the License for the specific language governing permissions and\n");
      out.write("    limitations under the License.\n");
      out.write(" -->\n");
 /* Author Andrew C. Oliver (acoliver2@users.sourceforge.net) */ 
      out.write("\n");
      out.write("<p align=\"center\">\n");
      out.write("\t<!-- ");
      out.print(appfooter);
      out.write(" -->\n");
      out.write("</p>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
